name: Build Site with Eleventy
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - name: Git Checkout
       uses: actions/checkout@v3
     - name: Setup Node and Yarn
       uses: actions/setup-node@v4
       with:
         cache: yarn
         node-version-file: package.json
     - run: yarn install --frozen-lockfile
     - run: yarn build
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         publish_dir: _site
         publish_branch: gh-pages
         github_token: ${{ secrets.GITHUB_TOKEN }}
